#!/usr/bin/python
# -*- coding:utf-8 -*-
#
# ini file  configure update script.
#
# - code by Jioh L. Jung (ziozzang@gmail.com)
#

import sys

def parse_argv(p):
  f = False
  o = []
  q = []
  q.append(p[0])
  for i in p[1:]:
    if not f:
      if i[:2] == "--":
        o.append(i[2:])
      else:
        f = True
        q.append(i)
    else:
      q.append(i)
  return (q,o)

def get_kv(lo):
  p = lo.find("=")
  if p == -1:
    return None
  k = i[:p].strip("# \t")
  v = i[p+1:].strip()
  return (k, v)


if __name__ == '__main__':
  sys.argv , opt = parse_argv(sys.argv)
  if len(sys.argv) != 4:
    print "Usage:\n # %s (options...) file key value" % sys.argv[0]
    exit(0)

  FILE_NAME = sys.argv[1]

  i = open(FILE_NAME, "r")
  f = i.read()
  i.close()

  w = open(FILE_NAME, "w")
  sp = False
  fn = False

  for i in f.splitlines(True):
    v = get_kv(i)
    if v is None:
      w.write(i)
    else:
      if v[0] == sys.argv[2]:
        w.write("%s=%s\n" % (sys.argv[2], sys.argv[3]))
        fn = True
      else:
        w.write(i)
    sp = True

  if fn == False:
    w.write("\n%s=%s" % (sys.argv[2], sys.argv[3]))

  w.close()
