#!/usr/bin/python
# -*- coding:utf-8 -*-
#
# ini file  configure update script.
#
# - code by Jioh L. Jung (ziozzang@gmail.com)
#

import sys

initype = True
tokentype = "tab"
setquote = False

def parse_argv(p):
  f = False
  o = []
  q = []
  q.append(p[0])
  for i in p[1:]:
    if not f:
      if i[:2] == "--":
        o.append(i[2:])
      else:
        f = True
        q.append(i)
    else:
      q.append(i)
  return (q,o)

def get_kv(lo):
  p = lo.find("=")
  if p == -1:
    return None
  k = lo[:p].strip("# \t")
  v = lo[p+1:].strip()
  return (k, v)

def get_opt(opt,key):
  for i in opt:
    v = get_kv(i)
    if v is not None:
      if v[1].lower() == "yes" or v[1].lower() == "true":
        return True
      elif v[1].lower() == "no" or v[1].lower() == "false":
        return True
      else:
        return v[1]
    elif i == key:
      return True
  return False

def get_split(lo, sp=None):
  if sp is None:
    s = lo.split()
  else:
    s = lo.split(sp)

  if len(lo) == 0:
    return None
  k = s[0].strip("#")
  if sp is None
    v = lo[lo.find(s[0]) + len(s[0]):].strip()
  else:
    v = lo[lo.find(s[0]) + len(s[0]):].strip(sp)
  return (k,v)

if __name__ == '__main__':
  sys.argv , opt = parse_argv(sys.argv)
  if len(sys.argv) != 4:
    print "Usage:\n # %s (options...) file key value" % sys.argv[0]
    exit(0)

  FILE_NAME = sys.argv[1]

  i = open(FILE_NAME, "r")
  f = i.read()
  i.close()

  w = open(FILE_NAME, "w")
  sp = False
  fn = False
  
  qv = sys.argv[3]
  if setquote:
    qv = "\"" + qv + "\""

  if initype:
    for i in f.splitlines(True):
      v = get_kv(i)
      if v is None:
        w.write(i)
      else:
        if v[0] == sys.argv[2]:
          w.write("%s=%s\n" % (sys.argv[2], qv))
          fn = True
        else:
          w.write(i)
      sp = True
  
    if fn == False:
      w.write("\n%s=%s" % (sys.argv[2], qv))
  else:
    td = {"tap":"\t", "space":" ", "comma":"," }
    for i in f.splitlines(True):
      if tokentype == "space" or tokentype == "tab":
        v = get_split(i)
      else:
        v = get_split(i, sp=td[tokentype])
      if v is None:
        w.write(i)
      else:
        if v[0] == sys.argv[2]:
          w.write("%s%s%s\n" % (sys.argv[2], td[tokentype], qv))
          fn = True
        else:
          w.write(i)
      sp = True
  
    if fn == False:
      w.write("\n%s%s%s" % (sys.argv[2], td[tokentype], qv))

  w.close()
