#!/bin/bash
#
# Elastic Search Automatically Install Script. (Debian/Ubuntu)
#  - Code by Jioh L. Jung (ziozzang@gmail.com)
#

# Check Java Exist.
if [ ! -f "/usr/bin/java" ]; then
  echo "HELLO!"
fi

# Get Newest Version of Elastic Search File (deb file)
DN_PAGE="http://www.elasticsearch.org/download/"
ES_PREPATH="https://download.elasticsearch.org/[^\"]*.deb"
ES_PATH=`wget -qO- $DN_PAGE | grep -o $ES_PREPATH | head -n 1`

# Fetch File
TMPFILE=$(mktemp /tmp/XXXXXXXX.deb)
rm -f $TMPFILE
wget -N -c ${ES_PATH} -O $TMPFILE

# Install Package
dpkg -ivf $TMPFILE
