#!/bin/bash
#
# mongodb Insall
#  - Code by Jioh L. Jung (ziozzang@gmail.com)
#

# 10gen repository

echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" > \
  /etc/apt/sources.list.d/mongodb.list

# Add Key
apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

# Repo Update
apt-get update
apt-get install -fy mongodb-10gen

update-rc.d mongodb enable
service mongodb restart
