#!/usr/bin/python

import sys

ssf = False
wrf = False
wcf = False



ap = ""
if len(sys.argv) < 3:
  print "Usage :\n # %s section key values ...." % sys.argv[0]
  exit(0)
if len(sys.argv) > 3:
  ap = " ".join(sys.argv[3:])

f = open("/etc/haproxy/haproxy.cfg","r").read()
t = open("/etc/haproxy/haproxy.cfg.tmp","w")
for i in f.splitlines(True):
  if len(i.strip()) == 0:
    # Blank lines
    t.write(i)
  elif i.strip()[0] == "#":
    # Comment
    t.write(i)
  elif i[0].isspace():
    # Inner Section
    if ssf:
      # Only for matched section
      k = i.strip().split()[0]
      if sys.argv[2].lower() == k.lower():
        # matched key
        wrf = True
        wcf = True
        t.write("\t%s\t" % (sys.argv[2]) + ap + "\n")
        continue
    t.write(i)
  else:
    # Section
    sn = i.split("#")[0].strip()
    if sn.replace("\t"," ").lower() == sys.argv[1].replace("\t"," ").lower():
      # Same Section
      ssf = True
    elif ssf and (wrf == False):
      ssf = False
      wcf = True
      t.write("\t%s\t" % (sys.argv[2]) + ap + "\n")
    else:
      ssf = False
    t.write(i)

if wcf == False:
  t.write("%s\n" % sys.argv[1])
  t.write("\t%s\t" % (sys.argv[2]) + ap + "\n")
